### ISSUE TITLE
Sampling nu should be from square root of eta?

### ISSUE THREAD

**Issue by bangxiangyong** [kelrenmor/sta663-FinalProject-SGHMC#1]
When sampling new nu for each epoch: 

`nu = eta_chol @ np.random.normal(size=p).reshape(p,-1) # sample from MV normal`

Shouldn't it be multiplied by the square root of eta_chol instead:
`nu = np.sqrt(eta_chol) @ np.random.normal(size=p).reshape(p,-1) # sample from MV normal`

Referring to formulas in the paper (eqn 14 & 15), assuming M = 1,
nu = epsilon  * r
eta = epsilon^2 
Hence, epsilon = sqrt(eta).

Not following this, the samples will be unstable and drifts.

https://github.com/kelrenmor/sta663-FinalProject-SGHMC/blob/master/SGHMC/sghmc/sghmc_algorithm.py

**Comment by kelrenmor** [comment]
Yes, thank you! Fixed.
